
# SEO
title: Blank Space Developers
description: ""
url: "http://blankspacedev.com"
logo: "assests/img/logo_bs_square.png"
#image:

twitter:
  username: blankspacedev

#facebook:
  #app_id: 1234
  #publisher: 1234
  #admins: 1234

#google_site_verification

# social:
#   name:
#   links:

email: contact@blankspacedev.com
about: "Organizamos eventos para mejorar la comunidad de desarrolladores en nuestra ciudad. Creemos que expandir nuestras fronteras profesionales nos ayudará a todos, a la vez que mejorará nuestra visibilidad."

# CONFIG
baseurl: "/" # the subpath of your site, e.g. /blog
# github:
#   url: "http://127.0.0.1:4000/"

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  sass_dir: _sass

# Project structure config
permalink: /blog/:year/:title.html

include: ["_pages"]

collections:
  blog_categories:
    output: true
    permalink: /blog/category/:slug/
  blog_tags:
    output: true
    permalink: /blog/tag/:slug/

defaults:
  -
    scope:
      path: ""
      type: blog_categories
    values:
      layout: blog_category
  -
    scope:
      path: ""
      type: blog_tags
    values:
      layout: blog_tag
