
# SEO
title: Blank Space Developers
description: ""
url: "http://blankspacedev.com"
logo: "assests/img/logo_bs_square.png"
#image:

twitter:
  username: blankspacedev

#facebook:
  #app_id: 1234
  #publisher: 1234
  #admins: 1234

#google_site_verification

# social:
#   name:
#   links:

address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: contact@blankspacedev.com
tel: +34 8493-4893
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: github
    url:

# CONFIG
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000/"

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  sass_dir: _sass

# Project structure config
permalink: /blog/:year/:title.html

include: ["_pages"]

collections:
  blog_categories:
    output: true
    permalink: /blog/category/:slug/
  blog_tags:
    output: true
    permalink: /blog/tag/:slug/

defaults:
  -
    scope:
      path: ""
      type: blog_categories
    values:
      layout: blog_category
  -
    scope:
      path: ""
      type: blog_tags
    values:
      layout: blog_tag
